language: python
python:
  - "3.6"
#  - "3.7" # travis doesn't support 3.7 yet.
# command to install dependencies
install:
    - pip install .
    - pip install .[testing]
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
